#http.cors.allow-origin: "/.*/"
#http.cors.enabled: true

# Cluster / Node Basics
cluster.name: elasticone

# Node can have abritrary attributes we can use for routing
node.name: searchnode-02
#node.datacenter: amsterdam
#network.publish_host: 192.168.10.175
# Force all memory to be locked, forcing the JVM to never swap
#bootstrap.mlockall: true

#marvel.agent.exporter.es.hosts: ["127.0.0.1:9200"]
http.cors.enabled: true
http.cors.allow-origin: /((http|https):\/\/)(((operation.)(test.|dev.|mirror.|product.)(ethicall.cn))|localhost:(\d)*)/
#http.cors.allow-origin: /http://operation.dev.ethicall.cn/
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"
http.cors.allow-methods: GET,POST

#index.number_of_shards: 3
#index.number_of_replicas: 1
## Threadpool Settings ##
node.master: false
node.data: true 

# Search pool
#threadpool.search.type: fixed
#threadpool.search.size: 20
#threadpool.search.queue_size: 100

# Bulk pool
#threadpool.bulk.type: fixed
#threadpool.bulk.size: 2
#threadpool.bulk.queue_size: 300

# Index pool
#threadpool.index.type: fixed
#threadpool.index.size: 2
#threadpool.index.queue_size: 100

# Indices settings
#indices.memory.index_buffer_size: 30%
#indices.memory.min_shard_index_buffer_size: 12mb
#indices.memory.min_index_buffer_size: 96mb

# Cache Sizes
#indices.fielddata.cache.size: 15%
#indices.fielddata.cache.expire: 6h
#indices.cache.filter.size: 15%
#indices.cache.filter.expire: 6h

# Indexing Settings for Writes
#index.refresh_interval: 30s
#index.translog.flush_threshold_ops: 50000

# Minimum nodes alive to constitute an operational cluster
discovery.zen.minimum_master_nodes: 2
#discovery.zen.minimum_master_nodes: 3
#discovery.zen.ping.timeout: 100s
discovery.zen.fd.ping_timeout: 100s
#discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: [elasticsearch,es3,]
#discovery.zen.ping.unicast.hosts: ["10.252.250.168","10.252.170.235"]
#discovery.zen.ping.unicast.hosts: ["10.27.227.104"]
#discovery.zen.ping_timeout: 100s
#discovery.zen.fd.ping_timeout: 100s
#discovery.zen.join_timeout: 2000s
#discovery.zen.publish_timeout: 30s
#discovery.zen.commit_timeout: 30s
#xpack.security.audit.enabled: true
#xpack.security.enabled: false
xpack.security.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
#xpack.reporting.enabled: false
xpack.monitoring.enabled: true
