#http.cors.allow-origin: "/.*/"
#http.cors.enabled: true

# Cluster / Node Basics
cluster.name: elasticone

# Node can have abritrary attributes we can use for routing
node.name: searchnode-01
#node.datacenter: amsterdam
#network.publish_host: 192.168.10.175
# Force all memory to be locked, forcing the JVM to never swap
#bootstrap.mlockall: true

#marvel.agent.exporter.es.hosts: ["127.0.0.1:9200"]
http.cors.enabled: true
http.cors.allow-origin: /((http|https):\/\/)(((operation.)(test.|dev.|mirror.|product.)(ethicall.cn))|localhost:(\d)*)/
#http.cors.allow-origin: /http://operation.dev.ethicall.cn/
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"
http.cors.allow-methods: GET,POST

#index.number_of_shards: 3
#index.number_of_replicas: 1
## Threadpool Settings ##

# Search pool
#threadpool.search.type: fixed
#threadpool.search.size: 20
#threadpool.search.queue_size: 100

# Bulk pool
#threadpool.bulk.type: fixed
#threadpool.bulk.size: 2
#threadpool.bulk.queue_size: 300

# Index pool
#threadpool.index.type: fixed
#threadpool.index.size: 2
#threadpool.index.queue_size: 100

# Indices settings
#indices.memory.index_buffer_size: 30%
#indices.memory.min_shard_index_buffer_size: 12mb
#indices.memory.min_index_buffer_size: 96mb

# Cache Sizes
#indices.fielddata.cache.size: 15%
#indices.fielddata.cache.expire: 6h
#indices.cache.filter.size: 15%
#indices.cache.filter.expire: 6h

# Indexing Settings for Writes
#index.refresh_interval: 30s
#index.translog.flush_threshold_ops: 50000

# Minimum nodes alive to constitute an operational cluster
#discovery.zen.minimum_master_nodes: 1
#discovery.zen.minimum_master_nodes: 3
#discovery.zen.ping.timeout: 100s
#discovery.zen.fd.ping_timeout: 100s
#discovery.zen.ping.multicast.enabled: false
#discovery.zen.ping.unicast.hosts: ["10.252.250.168"]
#discovery.zen.ping.unicast.hosts: ["10.252.250.168","10.252.170.235"]
#discovery.zen.ping.unicast.hosts: ["10.27.227.104"]
#discovery.zen.ping_timeout: 100s
#discovery.zen.fd.ping_timeout: 100s
#discovery.zen.join_timeout: 2000s
#discovery.zen.publish_timeout: 30s
#discovery.zen.commit_timeout: 30s
#xpack.security.audit.enabled: true

readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:

    - name: "::LOGSTASH::"
      # auth_key is good for testing, but replace it with `auth_key_sha1`!
      auth_key: logstash:logstashethicallcn
      type: allow
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create","cluster:monitor/*"]
      indices: ["logstash-*", "<no-index>"]

    # We trust this server side component, full access granted via HTTP authentication
    - name: "::KIBANA-SRV::"
      # auth_key is good for testing, but replace it with `auth_key_sha1`!
      auth_key: elastic:elasticl@ethical.cn
# kibana:kibana
      type: allow
      #actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create","cluster:monitor/*"]
      #1indices: ["<no-index>", ".kibana", ".kibana-devnull", "logstash-*", "default"]

    # Logs in via HTTP Basic Authentication, has RW access to kibana but zero access to non-kibana actions.
    - name: "::RO+ DEVELOPER::"
      auth_key: rw:dev
      type: allow
      kibana_access: rw
      indices: ["<no-index>", ".kibana", ".kibana-devnull", "logstash-*", "default"]

    # Cannot configure or edit dashboards and visualizations.
    - name: "::RO DEVELOPER::"
      auth_key: ethicall:o0lQc7l*48U$XnRd
      type: allow
      kibana_access: ro
      indices: ["*ethicall*"]

    # No authentication required to read from this index
    - name: "::PUBLIC SEARCH::"
      type: allow
      indices: ["public", "<no-index>",".kibana",".kibana-devnull"]
      actions: ["indices:data/read/*"]


###repo
path.repo: ["/usr/share/elasticsearch/data/backup"]
