FROM hub.local.ethicall.cn/elkstack/kibana:5.1.1 
#ADD ./x-pack-5.1.1.zip /tmp 
#RUN /usr/share/kibana/bin/kibana-plugin install file:///tmp/x-pack-5.1.1.zip
#RUN /usr/share/kibana/bin/kibana-plugin install x-pack
